### ISSUE TITLE
Error with non-existent index

### ISSUE THREAD

**Issue by Musa-Rabiu** [starsimhub/starsim#461]
Stack trace:
```py
(C:\Users\rabiu\anaconda3) C:\Users\rabiu>python
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> import starsim as ss
Starsim 0.3.2 (2024-04-08) — © 2023-2024 by IDM
>>> ss.demo()


—————————————
Running demo:
—————————————

Initializing sim with 10000 agents
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\sim.py", line 979, in demo
    sim.run()
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\sim.py", line 530, in run
    self.initialize()
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\sim.py", line 102, in initialize
    self.init_diseases()
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\sim.py", line 356, in init_diseases
    disease.initialize(self)
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\disease.py", line 41, in initialize
    self.set_initial_states(sim)
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\disease.py", line 215, in set_initial_states
    self.set_prognoses(sim, initial_cases)  # TODO: sentinel value to indicate seeds?
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\diseases\sir.py", line 71, in set_prognoses
    self.ti_dead[dead_uids] = sim.ti + dur_inf[will_die] / sim.dt # Consider rand round, but not CRN safe
  File "C:\Users\rabiu\anaconda3\lib\site-packages\starsim\states.py", line 230, in __setitem__
    return self._set_vals_uids_multiple(self.values, key, self._uid_map.__array__(), value.__array__())
  File "C:\Users\rabiu\anaconda3\lib\site-packages\numba\core\dispatcher.py", line 480, in _compile_for_args
    error_rewrite(e, 'constant_inference')
  File "C:\Users\rabiu\anaconda3\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.ConstantInferenceError: Failed in nopython mode pipeline (step: nopython rewrites)
no single definition for 'errormsg'

File "anaconda3\lib\site-packages\starsim\states.py", line 151:
    def _set_vals_uids_multiple(vals, key, uid_map, value):
        <source elided>
                errormsg = f'Attempted to write to a non-existant index ({idx}) - this can happen if attempting to write to new entries that have not yet been allocated via grow()'
                raise IndexError(errormsg)
                ^
```
System:
```py
>>> import sciris as sc
>>> sc.metadata()
#0. 'version':      None
#1. 'timestamp':    '2024-Apr-15 13:08:30'
#2. 'user':         'rabiu'
#3. 'system':
    #0. 'platform':   'Windows-10-10.0.22631-SP0'
    #1. 'executable': 'C:\\Users\\rabiu\\anaconda3\\python.exe'
    #2. 'version':    '3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023,
    18:18:15) [MSC v.1916 64 bit (AMD64)]'
#4. 'versions':
    #0. 'python':     '3.10.9'
    #1. 'sciris':     '3.1.6'
    #2. 'numpy':      '1.23.5'
    #3. 'pandas':     '2.1.4'
    #4. 'matplotlib': '3.7.0'
#5. 'calling_info':
    #0. 'filename': 'N/A'
    #1. 'lineno':   'N/A'
#6. 'git_info':
    #0. 'branch': 'Branch N/A'
    #1. 'hash':   'Hash N/A'
    #2. 'date':   'Date N/A'
#7. 'pipfreeze':    {'Automat': '20.2.0', 'Babel': '2.11.0', 'Bottleneck':
'1.3.5', 'Flask': '2.2.2', 'GitPython': '3.1.43', 'HeapDict': '1.0.1', 'Jinja2':
'3.1.2', 'Mako': '1.3.3', 'Markdown': '3.4.1', 'MarkupSafe': '2.1.1', 'Protego':
'0.1.16', 'PyDispatcher': '2.0.5', 'PyHamcrest': '2.0.2', 'PyJWT': '2.4.0',
'PyNaCl': '1.5.0', 'PyQt5': '5.15.10', 'PyQt5-sip': '12.13.0', 'PyQtWebEngine':
'5.15.6', 'PySocks': '1.7.1', 'PyWavelets': '1.4.1', 'PyYAML': '6.0',
'Pygments': '2.11.2', 'QDarkStyle': '3.0.2', 'QtAwesome': '1.2.2', 'QtPy':
'2.2.0', 'Rtree': '1.0.1', 'SQLAlchemy': '1.4.39', 'Scrapy': '2.8.0',
'Send2Trash': '1.8.0', 'Sphinx': '5.0.2', 'TBB': '0.2', 'Twisted': '22.2.0',
'Unidecode': '1.2.0', 'Werkzeug': '2.2.2', 'XlsxWriter': '3.2.0', 'alabaster':
'0.7.12', 'alembic': '1.13.1', 'anaconda-anon-usage': '0.4.4', 'anaconda-
client': '1.11.2', 'anaconda-cloud-auth': '0.5.0', 'anaconda-navigator':
'2.5.4', 'anaconda-project': '0.11.1', 'anyio': '3.5.0', 'appdirs': '1.4.4',
'argon2-cffi': '21.3.0', 'argon2-cffi-bindings': '21.2.0', 'arrow': '1.2.3',
'astroid': '2.14.2', 'astropy': '5.1', 'asttokens': '2.0.5', 'atomicwrites':
'1.4.0', 'attrs': '22.1.0', 'autopep8': '1.6.0', 'backcall': '0.2.0',
'backports.functools-lru-cache': '1.6.4', 'backports.tempfile': '1.0',
'backports.weakref': '1.0.post1', 'bcrypt': '3.2.0', 'beautifulsoup4': '4.11.1',
'binaryornot': '0.4.4', 'black': '22.6.0', 'bleach': '4.1.0', 'bokeh': '2.4.3',
'boltons': '23.0.0', 'brotlipy': '0.7.0', 'certifi': '2024.2.2', 'cffi':
'1.15.1', 'chardet': '4.0.0', 'charset-normalizer': '2.0.4', 'click': '8.0.4',
'cloudpickle': '2.0.0', 'clyent': '1.2.2', 'colorama': '0.4.6', 'colorcet':
'3.0.1', 'colorlog': '6.8.2', 'comm': '0.1.2', 'conda': '23.3.1', 'conda-build':
'3.24.0', 'conda-content-trust': '0.1.3', 'conda-pack': '0.6.0', 'conda-package-
handling': '2.0.2', 'conda-repo-cli': '1.0.41', 'conda-token': '0.4.0', 'conda-
verify': '3.4.2', 'conda_package_streaming': '0.7.0', 'constantly': '15.1.0',
'contourpy': '1.0.5', 'cookiecutter': '1.7.3', 'cryptography': '39.0.1',
'cssselect': '1.1.0', 'cycler': '0.11.0', 'cytoolz': '0.12.0', 'daal4py':
'2023.0.2', 'dask': '2022.7.0', 'datashader': '0.14.4', 'datashape': '0.5.4',
'debugpy': '1.5.1', 'decorator': '5.1.1', 'defusedxml': '0.7.1', 'diff-match-
patch': '20200713', 'dill': '0.3.8', 'distributed': '2022.7.0', 'docstring-to-
markdown': '0.11', 'docutils': '0.18.1', 'entrypoints': '0.4', 'et-xmlfile':
'1.1.0', 'executing': '0.8.3', 'fastjsonschema': '2.16.2', 'filelock': '3.9.0',
'flake8': '6.0.0', 'flit_core': '3.6.0', 'fonttools': '4.25.0', 'fpsim':
'0.22.0', 'fsspec': '2022.11.0', 'future': '0.18.3', 'gensim': '4.3.0', 'gitdb':
'4.0.11', 'glob2': '0.7', 'greenlet': '2.0.1', 'h5py': '3.7.0', 'holoviews':
'1.15.4', 'huggingface-hub': '0.10.1', 'hvplot': '0.8.2', 'hyperlink': '21.0.0',
'idna': '3.4', 'imagecodecs': '2021.8.26', 'imageio': '2.26.0', 'imagesize':
'1.4.1', 'imbalanced-learn': '0.10.1', 'importlib-metadata': '4.11.3',
'incremental': '21.3.0', 'inflection': '0.5.1', 'iniconfig': '1.1.1', 'intake':
'0.6.7', 'intervaltree': '3.1.0', 'ipykernel': '6.19.2', 'ipython': '8.10.0',
'ipython-genutils': '0.2.0', 'ipywidgets': '7.6.5', 'isort': '5.9.3',
'itemadapter': '0.3.0', 'itemloaders': '1.0.4', 'itsdangerous': '2.0.1', 'jedi':
'0.18.1', 'jellyfish': '0.9.0', 'jinja2-time': '0.2.0', 'jmespath': '0.10.0',
'joblib': '1.1.1', 'json5': '0.9.6', 'jsonpatch': '1.32', 'jsonpickle': '3.0.3',
'jsonpointer': '2.1', 'jsonschema': '4.17.3', 'jupyter': '1.0.0', 'jupyter-
console': '6.6.2', 'jupyter-server': '1.23.4', 'jupyter_client': '7.3.4',
'jupyter_core': '5.2.0', 'jupyterlab': '3.5.3', 'jupyterlab-pygments': '0.1.2',
'jupyterlab-widgets': '1.0.0', 'jupyterlab_server': '2.19.0', 'keyring':
'23.4.0', 'kiwisolver': '1.4.4', 'lazy-object-proxy': '1.6.0', 'libarchive-c':
'2.9', 'line-profiler': '4.1.2', 'llvmlite': '0.39.1', 'locket': '1.0.0',
'lxml': '4.9.1', 'lz4': '3.1.3', 'matplotlib': '3.7.0', 'matplotlib-inline':
'0.1.6', 'mccabe': '0.7.0', 'memory-profiler': '0.61.0', 'menuinst': '1.4.19',
'mistune': '0.8.4', 'mizani': '0.11.1', 'mkl-fft': '1.3.1', 'mkl-random':
'1.2.2', 'mkl-service': '2.4.0', 'mock': '4.0.3', 'mpmath': '1.2.1', 'msgpack':
'1.0.3', 'multipledispatch': '0.6.0', 'multiprocess': '0.70.16', 'munkres':
'1.1.4', 'mypy-extensions': '0.4.3', 'navigator-updater': '0.3.0', 'nbclassic':
'0.5.2', 'nbclient': '0.5.13', 'nbconvert': '6.5.4', 'nbformat': '5.7.0', 'nest-
asyncio': '1.5.6', 'networkx': '2.8.4', 'nltk': '3.7', 'notebook': '6.5.2',
'notebook_shim': '0.2.2', 'numba': '0.56.4', 'numexpr': '2.8.4', 'numpy':
'1.23.5', 'numpydoc': '1.5.0', 'openpyxl': '3.0.10', 'optuna': '3.6.1',
'packaging': '22.0', 'pandas': '2.2.1', 'pandocfilters': '1.5.0', 'panel':
'0.14.3', 'param': '1.12.3', 'paramiko': '2.8.1', 'parsel': '1.6.0', 'parso':
'0.8.3', 'partd': '1.2.0', 'pathlib': '1.0.1', 'pathspec': '0.10.3', 'patsy':
'0.5.6', 'pep8': '1.7.1', 'pexpect': '4.8.0', 'pickleshare': '0.7.5', 'pillow':
'10.2.0', 'pip': '22.3.1', 'pkce': '1.0.3', 'pkginfo': '1.9.6', 'platformdirs':
'2.5.2', 'plotly': '5.9.0', 'plotnine': '0.13.4', 'pluggy': '1.0.0', 'ply':
'3.11', 'pooch': '1.4.0', 'poyo': '0.5.0', 'prometheus-client': '0.14.1',
'prompt-toolkit': '3.0.36', 'psutil': '5.9.0', 'ptyprocess': '0.7.0', 'pure-
eval': '0.2.2', 'py': '1.11.0', 'pyOpenSSL': '23.0.0', 'pyarrow': '15.0.2',
'pyasn1': '0.4.8', 'pyasn1-modules': '0.2.8', 'pycodestyle': '2.10.0',
'pycosat': '0.6.4', 'pycparser': '2.21', 'pyct': '0.5.0', 'pycurl': '7.45.1',
'pydantic': '1.10.12', 'pydocstyle': '6.3.0', 'pyerfa': '2.0.0', 'pyflakes':
'3.0.1', 'pylint': '2.16.2', 'pylint-venv': '2.3.0', 'pyls-spyder': '0.4.0',
'pyodbc': '4.0.34', 'pyparsing': '3.0.9', 'pyrsistent': '0.18.0', 'pytest':
'7.1.2', 'python-dateutil': '2.8.2', 'python-dotenv': '0.21.0', 'python-lsp-
black': '1.2.1', 'python-lsp-jsonrpc': '1.0.0', 'python-lsp-server': '1.7.1',
'python-slugify': '5.0.2', 'python-snappy': '0.6.1', 'pytoolconfig': '1.2.5',
'pytz': '2022.7', 'pyviz-comms': '2.0.2', 'pywin32': '305.1', 'pywin32-ctypes':
'0.2.0', 'pywinpty': '2.0.10', 'pyzmq': '23.2.0', 'qstylizer': '0.2.2',
'qtconsole': '5.4.0', 'queuelib': '1.5.0', 'regex': '2022.7.9', 'requests':
'2.28.1', 'requests-file': '1.5.1', 'requests-toolbelt': '0.9.1', 'rope':
'1.7.0', 'ruamel-yaml-conda': '0.17.21', 'ruamel.yaml': '0.17.21',
'ruamel.yaml.clib': '0.2.6', 'scikit-image': '0.19.3', 'scikit-learn': '1.2.1',
'scikit-learn-intelex': '20230228.214818', 'scipy': '1.10.0', 'sciris': '3.1.6',
'seaborn': '0.12.2', 'semver': '3.0.2', 'service-identity': '18.1.0',
'setuptools': '65.6.3', 'sip': '6.7.12', 'six': '1.16.0', 'smart-open': '5.2.1',
'smmap': '5.0.1', 'sniffio': '1.2.0', 'snowballstemmer': '2.2.0',
'sortedcontainers': '2.4.0', 'soupsieve': '2.3.2.post1', 'sphinxcontrib-
applehelp': '1.0.2', 'sphinxcontrib-devhelp': '1.0.2', 'sphinxcontrib-htmlhelp':
'2.0.0', 'sphinxcontrib-jsmath': '1.0.1', 'sphinxcontrib-qthelp': '1.0.3',
'sphinxcontrib-serializinghtml': '1.1.5', 'spyder': '5.4.1', 'spyder-kernels':
'2.4.1', 'stack-data': '0.2.0', 'starsim': '0.3.2', 'statsmodels': '0.14.1',
'sympy': '1.11.1', 'tables': '3.7.0', 'tabulate': '0.8.10', 'tblib': '1.7.0',
'tenacity': '8.0.1', 'terminado': '0.17.1', 'text-unidecode': '1.3',
'textdistance': '4.2.1', 'threadpoolctl': '2.2.0', 'three-merge': '0.1.1',
'tifffile': '2021.7.2', 'tinycss2': '1.2.1', 'tldextract': '3.2.0',
'tokenizers': '0.11.4', 'toml': '0.10.2', 'tomli': '2.0.1', 'tomlkit': '0.11.1',
'toolz': '0.12.0', 'torch': '1.12.1', 'tornado': '6.1', 'tqdm': '4.64.1',
'traitlets': '5.7.1', 'transformers': '4.24.0', 'twisted-iocpsupport': '1.0.2',
'typing_extensions': '4.4.0', 'tzdata': '2024.1', 'ujson': '5.4.0', 'urllib3':
'1.26.14', 'w3lib': '1.21.0', 'watchdog': '2.1.6', 'wcwidth': '0.2.5',
'webencodings': '0.5.1', 'websocket-client': '0.58.0', 'whatthepatch': '1.0.2',
'wheel': '0.38.4', 'widgetsnbextension': '3.5.2', 'win-inet-pton': '1.1.0',
'wincertstore': '0.2', 'wrapt': '1.14.1', 'xarray': '2022.11.0', 'xlwings':
'0.29.1', 'yapf': '0.31.0', 'zict': '2.1.0', 'zipp': '3.11.0', 'zope.interface':
'5.4.0', 'zstandard': '0.19.0'}
#8. 'require':      None
#9. 'comments':     None
```

**Comment by cliffckerr** [comment]
Can reproduce:
```yaml
name: ssdebug
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - python=3.10.9=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - alabaster==0.7.12
      - alembic==1.13.1
      - anyio==3.5.0
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astroid==2.14.2
      - astropy==5.1
      - asttokens==2.0.5
      - atomicwrites==1.4.0
      - attrs==22.1.0
      - automat==20.2.0
      - autopep8==1.6.0
      - babel==2.11.0
      - backcall==0.2.0
      - backports-functools-lru-cache==1.6.4
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==3.2.0
      - beautifulsoup4==4.11.1
      - binaryornot==0.4.4
      - black==24.4.0
      - bleach==4.1.0
      - bokeh==2.4.3
      - boltons==23.0.0
      - bottleneck==1.3.5
      - brotlipy==0.7.0
      - certifi==2024.2.2
      - cffi==1.15.1
      - chardet==4.0.0
      - charset-normalizer==2.0.4
      - click==8.0.4
      - cloudpickle==2.0.0
      - colorcet==3.0.1
      - colorlog==6.8.2
      - comm==0.1.2
      - constantly==15.1.0
      - contourpy==1.0.5
      - cookiecutter==1.7.3
      - cryptography==39.0.1
      - cssselect==1.1.0
      - cycler==0.11.0
      - cytoolz==0.12.0
      - dask==2022.7.0
      - datashader==0.14.4
      - datashape==0.5.2
      - debugpy==1.5.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diff-match-patch==20200713
      - dill==0.3.8
      - distributed==2022.7.0
      - docstring-to-markdown==0.11
      - docutils==0.18.1
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - executing==0.8.3
      - fastjsonschema==2.16.2
      - filelock==3.9.0
      - flake8==6.0.0
      - flask==2.2.2
      - flit-core==3.6.0
      - fonttools==4.25.0
      - fsspec==2022.11.0
      - fst-pso==1.8.1
      - future==0.18.3
      - fuzzytm==2.0.5
      - gensim==4.3.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glob2==0.7
      - greenlet==2.0.1
      - h5py==3.7.0
      - heapdict==1.0.1
      - holoviews==1.17.1
      - huggingface-hub==0.17.3
      - hvplot==0.8.2
      - hyperlink==21.0.0
      - idna==3.4
      - imagecodecs==2021.8.26
      - imageio==2.26.0
      - imagesize==1.4.1
      - imbalanced-learn==0.10.1
      - importlib-metadata==4.11.3
      - incremental==21.3.0
      - inflection==0.5.1
      - iniconfig==1.1.1
      - intake==0.6.7
      - intervaltree==3.1.0
      - ipykernel==6.20.2
      - ipython==8.18.0
      - ipython-genutils==0.2.0
      - isort==5.9.3
      - itemadapter==0.3.0
      - itemloaders==1.0.4
      - itsdangerous==2.0.1
      - jedi==0.18.1
      - jeepney==0.8.0
      - jellyfish==0.9.0
      - jinja2==3.1.2
      - jinja2-time==0.2.0
      - jmespath==0.10.0
      - joblib==1.1.1
      - json5==0.9.6
      - jsonpatch==1.32
      - jsonpickle==3.0.3
      - jsonpointer==2.1
      - jsonschema==4.17.3
      - jupyter-client==7.3.4
      - jupyter-core==5.7.2
      - keyring==23.4.0
      - kiwisolver==1.4.4
      - lazy-object-proxy==1.6.0
      - libarchive-c==2.9
      - line-profiler==4.1.2
      - llvmlite==0.39.1
      - locket==1.0.0
      - lxml==4.9.1
      - lz4==3.1.3
      - mako==1.3.3
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.7.0
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      - memory-profiler==0.61.0
      - miniful==0.0.6
      - mistune==0.8.4
      - mizani==0.11.1
      - mock==4.0.3
      - mpmath==1.2.1
      - msgpack==1.0.3
      - multipledispatch==0.6.0
      - multiprocess==0.70.16
      - munkres==1.1.4
      - mypy-extensions==0.4.3
      - nest-asyncio==1.5.6
      - networkx==2.8.4
      - nltk==3.7
      - numba==0.56.4
      - numexpr==2.8.4
      - numpy==1.23.5
      - numpydoc==1.5.0
      - openpyxl==3.0.10
      - optuna==3.6.1
      - packaging==22.0
      - pandas==2.2.1
      - pandocfilters==1.5.0
      - panel==0.14.3
      - param==1.12.3
      - paramiko==2.8.1
      - parsel==1.6.0
      - parso==0.8.3
      - partd==1.2.0
      - pathlib==1.0.1
      - pathspec==0.10.3
      - patsy==0.5.6
      - pep8==1.7.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pip==22.3.1
      - pkce==1.0.3
      - pkginfo==1.9.6
      - platformdirs==2.5.2
      - plotly==5.9.0
      - plotnine==0.13.4
      - pluggy==1.0.0
      - ply==3.11
      - pooch==1.4.0
      - poyo==0.5.0
      - prometheus-client==0.14.1
      - prompt-toolkit==3.0.36
      - protego==0.1.16
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - pyarrow==15.0.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycodestyle==2.10.0
      - pycparser==2.21
      - pyct==0.5.0
      - pycurl==7.45.1
      - pydantic==1.10.12
      - pydispatcher==2.0.5
      - pydocstyle==6.3.0
      - pyerfa==2.0.0
      - pyflakes==3.0.1
      - pyfume==0.3.1
      - pygments==2.11.2
      - pyhamcrest==2.0.2
      - pyjwt==2.4.0
      - pylint==2.16.2
      - pylint-venv==2.3.0
      - pyls-spyder==0.4.0
      - pynacl==1.5.0
      - pyodbc==4.0.34
      - pyopenssl==23.0.0
      - pyparsing==3.0.9
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqtwebengine==5.15.6
      - pyqtwebengine-qt5==5.15.2
      - pyrsistent==0.18.0
      - pysocks==1.7.1
      - pytest==7.1.2
      - python-dateutil==2.8.2
      - python-dotenv==0.21.0
      - python-lsp-black==1.2.1
      - python-lsp-jsonrpc==1.0.0
      - python-lsp-server==1.7.1
      - python-slugify==5.0.2
      - python-snappy==0.6.1
      - pytoolconfig==1.2.5
      - pytz==2022.7
      - pyviz-comms==2.0.2
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==23.2.0
      - qdarkstyle==3.0.2
      - qstylizer==0.2.2
      - qtawesome==1.2.2
      - qtconsole==5.4.0
      - qtpy==2.2.0
      - queuelib==1.5.0
      - regex==2022.7.9
      - requests==2.28.1
      - requests-file==1.5.1
      - requests-toolbelt==0.9.1
      - rope==1.7.0
      - rtree==1.0.1
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - sciris==3.1.6
      - scrapy==2.8.0
      - seaborn==0.12.2
      - secretstorage==3.3.3
      - semver==3.0.2
      - send2trash==1.8.0
      - service-identity==18.1.0
      - setuptools==65.6.3
      - simpful==2.12.0
      - sip==6.7.12
      - six==1.16.0
      - smart-open==5.2.1
      - smmap==5.0.1
      - sniffio==1.2.0
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.3.2.post1
      - sphinx==5.0.2
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==1.4.39
      - stack-data==0.2.0
      - starsim==0.3.2
      - statsmodels==0.14.1
      - sympy==1.11.1
      - tables==3.7.0
      - tabulate==0.8.10
      - tblib==1.7.0
      - tenacity==8.0.1
      - terminado==0.17.1
      - text-unidecode==1.3
      - textdistance==4.2.1
      - threadpoolctl==2.2.0
      - three-merge==0.1.1
      - tifffile==2021.7.2
      - tinycss2==1.2.1
      - tldextract==3.2.0
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.0.1
      - tomlkit==0.11.1
      - toolz==0.12.0
      - tornado==6.1
      - tqdm==4.64.1
      - traitlets==5.7.1
      - transformers==4.24.0
      - twisted==22.10.0
      - typing-extensions==4.4.0
      - tzdata==2024.1
      - ujson==5.4.0
      - unidecode==1.2.0
      - urllib3==1.26.14
      - w3lib==1.21.0
      - watchdog==2.1.6
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==0.58.0
      - werkzeug==2.2.2
      - whatthepatch==1.0.2
      - wheel==0.38.4
      - win-inet-pton==1.1.0
      - wincertstore==0.2
      - wrapt==1.14.1
      - xarray==2022.11.0
      - xlsxwriter==3.2.0
      - xlwings==0.29.1
      - yapf==0.31.0
      - zict==2.1.0
      - zipp==3.11.0
      - zope-interface==5.4.0
      - zstandard==0.19.0
prefix: /software/anaconda3/envs/ssdebug
```

**Comment by cliffckerr** [comment]
Simpler debug:
```sh
conda create -n debug python=3.10.9
pip install numpy==1.23.5 scipy==1.10.0 pandas==2.2.1 matplotlib==3.7.0 sciris==3.1.6 numba==0.56.4 networkx==2.8.4 starsim==0.3.2
```

**Comment by cliffckerr** [comment]
Issue is Numba; upgrading to 0.59.1 fixes it. Weird!
