### ISSUE TITLE
Debug Spyder-parallel run issue

### ISSUE THREAD

**Issue by cliffckerr** [starsimhub/starsim#663]
On Starsim commit `88d44fe`, this code:
```py
import starsim as ss

s1 = ss.Sim(diseases='sir', networks='random')
s2 = ss.Sim(diseases='sis', networks='random')

msim = ss.parallel(s1, s2)
```

sometimes fails with:
```py
Exception in thread Thread-12 (_handle_results):
Traceback (most recent call last):
  File "/software/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/software/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/software/anaconda3/lib/python3.11/site-packages/multiprocess/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/software/anaconda3/lib/python3.11/site-packages/multiprocess/connection.py", line 253, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/lib/python3.11/site-packages/dill/_dill.py", line 301, in loads
    return load(file, ignore, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/lib/python3.11/site-packages/dill/_dill.py", line 287, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/anaconda3/lib/python3.11/site-packages/dill/_dill.py", line 442, in load
    obj = StockUnpickler.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cliffk/sciris/sciris/sciris/sc_odict.py", line 1207, in __setitem__
    odict.__setitem__(self, name, value)
    ^^^^^
NameError: name 'odict' is not defined. Did you mean: 'dict'?
```

...but only on Spyder.

**Comment by cliffckerr** [comment]
Reinstalled `conda` and the problem went away ... not sure what it was, but hard to reproduce!
