### ISSUE TITLE
time_prob handling results in AttributeError

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#693]
Instead of computing an event probability the basic way, `p = beta * stuff`, where `beta` here is a `time_prob` (`ss.beta`), I would like to use the more accurate approximation, `p = 1 - exp(-beta * stuff)`.

However, `-beta` doesn't work:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dklein/GIT/starsim/starsim/timepars.py", line 298, in __neg__
    def __neg__(self): return self.asnew().set(v=-self.v)
  File "/Users/dklein/GIT/starsim/starsim/timepars.py", line 218, in set
    self.update_cached()
  File "/Users/dklein/GIT/starsim/starsim/timepars.py", line 233, in update_cached
    raise E
  File "/Users/dklein/GIT/starsim/starsim/timepars.py", line 226, in update_cached
    self.update_values()
  File "/Users/dklein/GIT/starsim/starsim/timepars.py", line 362, in update_values
    errormsg = f'Invalid value {self.value} for {self}: must be 0-1'
  File "/Users/dklein/GIT/starsim/starsim/arrays.py", line 35, in __getattr__
    return object.__getattribute__(self, 'values').__getattribute__(attr) # Be explicit to avoid possible recurison
AttributeError: 'numpy.float64' object has no attribute 'value'
```

**Comment by cliffckerr** [comment]
Fixed the bug and added a more helpful error message, pointing the user to `-beta.values`:
```py
ValueError: Invalid value -0.1 for ss.beta(-0.1, unit=None): must be 0-1. If using in a calculation, use .values instead.
```
