### ISSUE TITLE
Some distributions with callable params failing

### ISSUE THREAD

**Issue by daniel-klein** [starsimhub/starsim#827]
```python
import starsim as ss

# Make the SIR module
sir = ss.SIR(
    dur_inf = ss.lognorm_im(mean=lambda self, sim, uids: sim.people.age[uids] / 100),
    beta = ss.beta(0.2),
    p_death = ss.bernoulli(p=0.1),
)

sim = ss.Sim(n_agents = 2000,
    diseases = sir,
    networks = ss.RandomNet() )
sim.run()
```

results in
```bash
(py312) dklein@BMGF-G9RWH5WK5Q ~/Downloads$ /Users/dklein/miniforge3/envs/py312/bin/python /Users/dklein/Downloads/code.py
Initializing sim with 2000 agents
Traceback (most recent call last):
  File "/Users/dklein/Downloads/code.py", line 13, in <module>
    sim.run()
  File "/Users/dklein/GIT/starsim/starsim/sim.py", line 296, in run
    if not self.initialized: self.init()
                             ^^^^^^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/sim.py", line 145, in init
    self.init_dists() # Initialize distributions
    ^^^^^^^^^^^^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/sim.py", line 213, in init_dists
    self.dists.init(obj=self, base_seed=self.pars.rand_seed, force=True)
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 96, in init
    dist.init(trace=trace, seed=base_seed, sim=sim, force=force)
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 398, in init
    self.process_dist()
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 450, in process_dist
    spars = self.process_pars(call=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 496, in process_pars
    spars = self.sync_pars() # Synchronize parameters between the NumPy and SciPy distributions
            ^^^^^^^^^^^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 775, in sync_pars
    self.call_pars()
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 535, in call_pars
    val = self.call_par(key, val, size, uids)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 522, in call_par
    val = self.convert_callable(key, val, size, uids)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/distributions.py", line 512, in convert_callable
    out = val(self.module, self.sim, size_par)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dklein/Downloads/code.py", line 5, in <lambda>
    dur_inf = ss.lognorm_im(mean=lambda self, sim, uids: sim.people.age[uids] / 100),
                                                         ~~~~~~~~~~~~~~^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/arrays.py", line 228, in __getitem__
    key = self._convert_key(key)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dklein/GIT/starsim/starsim/arrays.py", line 219, in _convert_key
    elif not np.isscalar(key) and len(key) == 0: # Handle [], np.array([]), etc.
                                  ^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

Fix in arrays.py ~213:
        if key is None:
            return uids()

**Comment by cliffckerr** [comment]
Hm, I think this bug was introduced as an attempt to address #519 and #535. Closed by #831.
